### ISSUE TITLE
Method not found: 'Microsoft.Xna.Framework.Color.get_TransparentBlack()'

### ISSUE THREAD

**Issue by jamesla** [craftworkgames/MonoGame.Extended#807] opened 2023-04-24 18:00 UTC
Getting the following error when trying to follow the tiled documentation here:
https://www.monogameextended.net/docs/features/tiled/tiled

![image](https://user-images.githubusercontent.com/5243178/234078127-6d6a9950-d7d5-4894-816b-9e59a64cb874.png)

Have searched in the discord and it looks like a problem other people are having as there is a bit of talk about it but no resolution that I could see.

I have the following dependency versions installed:
![image](https://user-images.githubusercontent.com/5243178/234081679-195eb160-15dc-47e0-bea9-ad1b80a1d5d5.png)

and have installed the extended content pipeline dll as follows:
![image](https://user-images.githubusercontent.com/5243178/234078490-595629fe-97d5-438e-bb85-60f4894f4b6c.png)

it's breaking with the sample map from the docs so it's not something I'm doing wrong in tiled.

Anybody know how to resolve this?

**Comment by blouflashdb** [comment] 2023-05-23 19:17
I have the same issue. Would love to see someone help me out.

**Comment by blouflashdb** [comment] 2023-05-23 22:25
I solved this by using the pre-release rolling builds feed.
A NuGet.config is needed with the feed from the readme of this project:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>
    <config>
        <add key="globalPackagesFolder" value=".nuget\packages" />
    </config>
    <packageSources>
        <add key="lithiumtoast" value="https://www.myget.org/F/lithiumtoast/api/v3/index.json" />
        <add key="NuGet" value="https://api.nuget.org/v3/index.json" />
    </packageSources>
</configuration>`

As package version I set 3.9.0-alpha0093
`    <PackageReference Include="MonoGame.Extended.Tiled" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="3.9.0-alpha0093" />`

**Comment by Gandifil** [comment] 2023-09-03 14:17
Duplicate of #783

**Comment by AristurtleDev** [comment] 2024-05-28 02:39
This issue was caused due to the removal of `Color.TransparentBlack` in MonoGame 3.8.1.303.
This is no longer an issue in `develop` since it has been updated to the latest MonoGame version. 

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4

**Closed by AristurtleDev** 2024-05-28 02:39 UTC
Labels: bug
