### ISSUE TITLE
I can't import tsx (tileset tiled)

### ISSUE THREAD

**Issue by ElBidouilleur** [craftworkgames/MonoGame.Extended#812] opened 2023-07-08 21:44 UTC
Hello

I want to import tileset tiled but i've an error
I already test to passed monogame to 3.8.0 and is not work

![image](https://github.com/craftworkgames/MonoGame.Extended/assets/91120790/65d16c36-c2ab-4f2d-b031-11539dec650d)

I've the last version

![image](https://github.com/craftworkgames/MonoGame.Extended/assets/91120790/66e35d3c-591b-4ca1-95e9-0f6e8bb313d9)

Thanks

**Comment by Gandifil** [comment] 2023-09-03 14:13
May be, Duplicate of #783 . Please, check and answer here.

However, try to load dev version of Monogame.Extended. (instructions in README).

**Comment by simonsk90** [comment] 2023-10-11 11:48
Take a look at this maybe:

https://community.monogame.net/t/failed-to-build-map-tmx-file-with-monogame-extended/19561

**Comment by AristurtleDev** [comment] 2024-05-28 02:29
This issue was caused due to the removal of `Color.TransparentBlack` in MonoGame 3.8.1.303.
This is no longer an issue in `develop` since it has been updated to the latest MonoGame version. 

Until the MonoGame.Extended v4.0.0 release you can use one of the following workaround
1. Use the source code of MonoGame.Extended directly and reference it in your project
2. Use the most recent (at the time of writing this) prerelease NuGet https://www.nuget.org/packages/MonoGame.Extended/3.9.0-prerelease.4

**Closed by AristurtleDev** 2024-05-28 02:29 UTC
Labels: bug
