### ISSUE TITLE
Overflow on TiledMapImporter due to int instead of uint

### ISSUE THREAD

**Issue by lozzajp** [craftworkgames/MonoGame.Extended#324] opened 2016-12-16 13:16 UTC
See [this post](http://community.monogame.net/t/tiledmapimporter-fails-too-high-values/8525/8) on MG community page.

If a tile's "gidID" in a saved tmx/xml is beyond `int.Max` an `OverflowException` occurs during import.

Due to the way the xml stores swapped tiles the values can go much higher, Perhaps a `uint` should be used during import.

**Comment by craftworkgames** [comment] 2016-12-16 22:27
> It seems Tiled adds a high value as the "gidID" for a tile, indicating that they are flipped either 
> 1. horizontally (adds hex 0x80000000)
> 2. vertically (adds hex 0x40000000) or 
> 3. diagonally (adds hex 0x20000000)
>
> So 2147484247 (value stored as gid above) is 2147483648 (hex 0x80000000) + 599 (correct tileset ID).
>
> So just by subtracting the added hex value I can get my tile set IDs and find out how the tiles should be filpped when I laterdraw them. However TiledMapImporter fails before I get the chance to do so, so does anyone know if there is any support for handling the import with these high numbers?

I'm pretty sure this is the reason we are seeing this. 

Is anyone interested in fixing this? it shouldn't be too difficult.

The first thing we need, is a map with the problem. We can either add a new map to the demo or edit one of the existing ones.

1. Reproduce the issue.
2. Write a fix. 
3. Check the other demos to make sure nothing is broken.
4. Submit PR.

If you want to go one step further, also write a unit test.

**Comment by LithiumToast** [comment] 2016-12-20 07:02
I'll do this.

**Comment by LithiumToast** [comment] 2016-12-24 04:36
Found the bug. I'm updating the level01.tmx to have some flipped tiles.

**Comment by LithiumToast** [comment] 2016-12-27 21:44
This is fixed in my Tiled refactor branch. I'll do a pull request soon.

**Comment by LithiumToast** [comment] 2017-03-04 01:51
@craftworkgames This can be closed.

**Closed** 2017-03-04 11:32 UTC
Labels: bug, content pipeline, up-for-grabs
