### ISSUE TITLE
 SpriteSheetAnimation Requires an Update to Rewind

### ISSUE THREAD

**Issue by EReeves** [craftworkgames/MonoGame.Extended#659] opened 2020-03-05 15:22 UTC
Rewind() doesn't take effect in SpriteSheetAnimation until after an update.

It would make the Animation class more complicated, but Play Pause Stop and Rewind should probably be made virtual so that SpriteSheetAnimation can change its CurrentFrameIndex without waiting for Update to be called.

Right now if you want to stop and play an animation you have to use a coroutine or something after calling Stop/Rewind to wait for an Update, and then Play the animation.

It might be nice if you could set the current time too.

**Comment by lithiumtoast** [comment] 2020-06-30 13:13
OK, I see the problem is that the frame index is not updated directly when calling `Rewind`. I rather resolve this issue by revisiting the related code in its entirety. This won't happen until v4 when the code is split out into different repositories.

**Comment by AristurtleDev** [comment] 2024-06-24 03:17
This has been resolved in the sprite rework.

- AnimatedSprites can use the `Restart` method in place of the previous `Rewind`.
- Frame of animation can be set explicitly using `SetFrame`
- Each frame can now have it's own independent duration instead of a single duration definition for all frames.

**Closed by AristurtleDev** 2024-06-24 03:17 UTC
Labels: bug
