### ISSUE TITLE
Cannot build .tmx files. TiledMapTilesetProcessor showing a MissingMethodException

### ISSUE THREAD

**Issue by fhb93** [craftworkgames/MonoGame.Extended#783] opened 2022-08-12 15:39 UTC
Hello, I'm trying to migrate a project from Windows to an M1 Macbook Air, so I can handle adjustments to run my game on Intel & Apple Silicon hardware too. After setting everything up I've found that MGCB cannot build the TiledMap files into xnb. 
The mgcb build task stops in an System.MissingMethodException. After one day seeking for a fix, I downloaded and tried to build the Monogame Extended samples to check if the issue is happening only with my project. Below is the exact output from the CLI mgcb (Issue happens with MGCB-editor and CLI mgcb). The sample project in question is the Platformer one.

``/Users/username/Downloads/MonoGame.Extended-samples-master/src/Games/Platformer/Content/test-map.tmx: error: Processor 'TiledMapTilesetProcessor' had unexpected failure!
System.MissingMethodException: Method not found: 'Microsoft.Xna.Framework.Color Microsoft.Xna.Framework.Color.get_TransparentBlack()'.
   at MonoGame.Extended.Content.Pipeline.Tiled.TiledMapTilesetProcessor.Process(TiledMapTilesetContentItem contentItem, ContentProcessorContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentProcessor`2.Microsoft.Xna.Framework.Content.Pipeline.IContentProcessor.Process(Object input, ContentProcessorContext context) in /home/runner/work/MonoGame/MonoGame/MonoGame.Framework.Content.Pipeline/ContentProcessor.cs:line 60
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent) in /home/runner/work/MonoGame/MonoGame/MonoGame.Framework.Content.Pipeline/Builder/PipelineManager.cs:line 717``

Any ideas on what is going on? Thanks in advance 🙂

**Comment by devme0** [comment] 2022-08-20 13:24
I am facing the same issue :

![image](https://user-images.githubusercontent.com/13641219/185747818-d803ab08-3020-4f44-b2cf-8a168a7b9a43.png)

I am running on Windows 11 with Visual Studio 2022, the project uses the Android template. I am using an embedded tile set with a single tile set image for the tile map made using Tiled.

Referenced Versions:
```
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Extended" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended.Tiled" Version="3.8.0" />
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.1.303" />

```
The Content.mgcb file:

```

#----------------------------- Global Properties ----------------------------#

/outputDir:bin/$(Platform)
/intermediateDir:obj/$(Platform)
/platform:Android
/config:
/profile:Reach
/compress:False

#-------------------------------- References --------------------------------#

/reference:..\..\..\..\..\.nuget\packages\monogame.extended.content.pipeline\3.8.0\tools\MonoGame.Extended.Content.Pipeline.dll

#---------------------------------- Content ---------------------------------#

#begin Tile/gamemap.tmx
/importer:TiledMapImporter
/processor:TiledMapProcessor
/build:Tile/gamemap.tmx

#begin Tile/rect111.png
/importer:TextureImporter
/processor:TextureProcessor
/processorParam:ColorKeyColor=255,0,255,255
/processorParam:ColorKeyEnabled=True
/processorParam:GenerateMipmaps=False
/processorParam:PremultiplyAlpha=True
/processorParam:ResizeToPowerOfTwo=False
/processorParam:MakeSquare=False
/processorParam:TextureFormat=Color
/build:Tile/rect111.png


```
I have been at it for two days now, any help will be highly appreciated.

**Comment by devme0** [comment] 2022-08-20 16:28
Even downgrading the MonoGame.Content.Builder.Task and MonoGame.Framework.Android version to 3.8.0 still throws the same error:

```
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="3.8.0" />
    <PackageReference Include="MonoGame.Extended.Tiled" Version="3.8.0" />
    <PackageReference Include="MonoGame.Framework.Android" Version="3.8.0" />

```

**Comment by MetaFight** [comment] 2022-09-05 23:48
I found downgrading `mgcb` to version 3.7.0 fixed the issue, but unfortunately this left my pipeline artifacts in an unusable version.

**Comment by damian-666** [comment] 2022-09-06 01:51
hope this novella helps   #1.  I saw in the changes that Transparent Black
was removed as redundant. its  now just Color.Transparent.  because they
are both   0,0,0,0  .. but its a msssng symbol. wouldnt that explain the
error?.. mabye a global using might switch it ?   or    Just change that
symbol ibuild the source.    PRs like this are beng taken  in to MG core,
but well mabye they should be just as stubborn as before not to take in
stuff.. however it was becomng a mess , hard to maintain, so they did. .
BUT  consider mg 3.81. is NOT ..  what if you define static
Color.Transparent black in your code, as Color.Transparent, will it work?


  3.80 + 01 update, u expect a day on.. featurewise yes,  but
structurally has MANY breaking changes ...  expect WEEKS of work ...

#2  or .. if you really give in an revert and still didnt work
this sounds like a vs 2022 cache issue:     its subsequent builds are much
faster because its caching stuff by date..so if you revert code or refs,
might not get reverted results and go mad, so      try this  before
smashing ur PC...  find   delete all your user Cache files made by VS 2022
.. in user , and temp directories in  user your account there are tons of
artifacts that might supercede ur reversion..because tghe cache is newer.
     im using the VS 2022 latest  prevew and has similar issue after i
reverted code.   and even did a clean clone with changes i made that broke
something.. , and then deleted all the nuget stuff and the regress was
STILL THERE... But theres more artifacts:    . search your whole HD at
least ur user part,  for any extension, and sort by Date, around when
things went south ( when u updated) , u will see various files with cache
and other extension.. if its in User or Temp, its likely safe to delete.
 also   The GAC is barely used now but it used to matter.

   2.so even now, u might need to remove  more stuff  like config files and
json files, so it wll go back to the GAC....... there are MSBuild things
that tell nuget to "roll foward"     there as json config filles everywhere
to learn about if you have to .    and    if you really wanna downgrade
there is PATH order to worry about..  mabye when u reisntall the older
.net, its now later in the PATH..  the content manager directives are in a
.config at the top of the sln..  part of the update to mg 3,81 requires
unstilling netcore 3.1.. taht means if you put it back the path will be
after and i might use the new one.

the new MSBuild is better , simpler but completely different.        so..
well it sucks that things got broken so im detemined to move forward.   to
net6 adn 3.81 as they are suppossed to be LTS and 2 years supported.

3.   OR you can try building on windows and deploying on Mac?   the mac
verson has known content issues taht cannot be address and the devs
admitted they need to fix somethng for mac dev studio   some are embedded
the xnb products in Dlls and makng a custom  content manager like Nez has
been doing for years to get around this for now.

OR,   mabye try vs 2022 preview if yhou are using Vs 2022 release... or
vscode...its stable, faster,  and better but it caches even more. o ro vs
code.. is slow but doenst make caches.


4.  look at Nez core see if it still works wtih MG.. regardless,  He builds
content xnb, mabye and puts the XNB as embedded resource in a core dll
using custom content manager.    i dont like this , cause me other issues.
 and think they are close to getting content working right.  he has lots of
sprite sheets and tile maps stuff...

     Thsi all stuff that i learned after days and questioning my sanity and
all htat.    i told a guy about the cache files it worked for him too...
now.    im fightin with missing ..binding as well. somethingin SharpDX
wichis archived. now unsupported...  m gong to keep on MG. 3.81, get rid
net.48 fork and split MG / or wait for new bindings. but yet ive been
fighting 4 weeks over something though mght take 2 days.      but i had to
do th sooner or later.   anyways now i prolly need to trace the dead
elephant of sharpDX or move on and go back ot ths feature later MS wllll
change somethng. , because i cant use wpf interop with my docking system
even if the sample works... sighhh...
System.MissingMethodException: ‘Method not found: ‘IntPtr
Microsoft.Xna.Framework.Graphics.Texture.GetSharedHandle()’.’
<https://community.monogame.net/t/system-missingmethodexception-method-not-found-intptr-microsoft-xna-framework-graphics-texture-getsharedhandle/17894>

**Comment by MetaFight** [comment] 2022-09-06 07:33
Thanks for the nudge in the right direction.  I had a quick look at the mg-e code and it looks like the dependence on Color.TransparentBlack has already been removed.  I'll try to build a new Tiled pipeline extension (or whatever it's called) from the latest sources when I've got a bit of time.  Hopefully the issue is already fixed and we just need a new build/nuget package.

**Comment by MetaFight** [comment] 2022-09-16 18:30
Are you asking about the `Monogame.Extended.Content.Pipeline.dll` file?  I put it with my other project external dependencies.
I used the content editor to add a reference to it.
I think there's currently also a bug with relative paths not working in .mgcb files so you'll need to double check that the reference uses an absolute path.  I did this by opening the file in a text editor.

Hopefully that helps.

**Comment by damian-666** [comment] 2022-09-16 20:59
i have relative paths working but i put hte mgcb wiht the content in a shared net6 core..  then i link the mgcb to the exe project ... its relative so theres no internal relative path in the mgcb.. i dont link the assets themselves nor copy them.. they are set to None.. the content builder takes care of all that... ... i use ..\..bin not problem on windows as a base path  its min my ..https://github.com/damian-666/MGShadersXPlatform/blob/master/MGXPlatformNet6.sln sample and the files copy..    its important to have the new content builder and rebuld your project files if yo are moving to net6 you have to change tons of tooling and erase old stuff...  then new tool and msbuild is way better but it takes time.


 but im not using extended content or even mp3 yet.. my sample might help yoyu tho as it copies the content to the right places.    feel free to update it with mp3 and or whatever because there are no other new samples that show shared core multiplatfrom developement.. that is the only way to avoid repeat assets or code that i konw of and the simple sample  i started with .. is 3.1 netcore and 2 years old.. 


..   make sure you have the .config folder at your root....{
  "version": 1,
  "isRoot": true,
  "tools": {
    "dotnet-mgcb": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb"
      ]
    },
    "dotnet-mgcb-editor": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor"
      ]
    },
    "dotnet-mgcb-editor-linux": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-linux"
      ]
    },
    "dotnet-mgcb-editor-windows": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-windows"
      ]
    },
    "dotnet-mgcb-editor-mac": {
      "version": "3.8.1.303",
      "commands": [
        "mgcb-editor-mac"
      ]
    }
  }
}
 



im having trouble with https://github.com/craftworkgames/MonoGame.WpfControl in another vault....   i get mtheod not found.. * getShartedHaldle*  when i acces the rendertexture... in the view module.. its a sharpDX thing.. i think i have to bild monogame and then find out becausethe sample works i put a PR., and theer is another PR im gong to try his version.. . but im using legacy 48 components a detcore windows 6 exe and a  only DevCompnonetsRibbon docing system..  its using tabbed dialogs. ill put the issue there but tabbed dialgs were never supported... 

btw its 5 weeks and im 99 % though all this... its for 2 years LTS so i hope i dont have to do this again... the biggest pain for me was netstandard 2 dropped bu you can use old dependencies...  msft command line upgrade -assistant mgiht help also.. or it might make a mess...  the upside is my netcore6 libs are faster and projects cleaner.

**Comment by kolen** [comment] 2022-10-26 22:40
Seems that it's fixed in #735.

**Comment by MetaFight** [comment] 2022-10-26 23:17
https://github.com/craftworkgames/MonoGame.Extended/issues/783#issuecomment-1239998020

Indeed it does.  When I checked there wasn't a new build and MonoGame 3.8.1 wasn't supported yet.

**Comment by lithiumtoast** [comment] 2022-10-27 02:37
@kolen @MetaFight Latest builds are automatically deployed to MyGet. E.g. https://www.myget.org/feed/lithiumtoast/package/nuget/MonoGame.Extended/3.9.0-alpha0079.

**Comment by 8bitAlex** [comment] 2023-03-18 05:05
+1 still an issue

**Comment by iNewmanity** [comment] 2023-03-20 22:51
Yeah, got this error too. Does anyone now, if the TileMap-Object is compatible with the TMX one from tiledsharp?

**Comment by DesdeJorge** [comment] 2023-04-01 20:50
I have the same error with monogame 3.8.1 and extended 3.8.0, any solution?

**Comment by Lalayqz** [comment] 2023-04-05 12:14
My problem got solved by upgrading MonoGame.Extended & MonoGame.Extended.Content.Pipeline & MonoGame.Extended.Tiled to 3.9.0-alpha0093.

**Comment by iNewmanity** [comment] 2023-04-06 23:51
> My problem got solved by upgrading MonoGame.Extended & MonoGame.Extended.Content.Pipeline & MonoGame.Extended.Tiled to 3.9.0-alpha0093.

Could you please tell me, how to do it? Last Time i tried this, i got an error. I need this to work! Thank you in advance!

**Comment by Lalayqz** [comment] 2023-04-07 02:11
> > My problem got solved by upgrading MonoGame.Extended & MonoGame.Extended.Content.Pipeline & MonoGame.Extended.Tiled to 3.9.0-alpha0093.
> 
> Could you please tell me, how to do it? Last Time i tried this, i got an error. I need this to work! Thank you in advance!

I'm not an expert at this, but here's what I did.
In Visual Studio, use the search bar on the top go to the "Manage NuGet Packages..." page.
Then add a new "MyGet" package source there, because alpha builds are deployed to "MyGet", not the default "nuget.org".
![image](https://user-images.githubusercontent.com/79684981/230526029-cfbaaa5a-1479-4ad5-8ffe-ade96b5c8562.png)

Then upgrade to alpha builds using this "MyGet" package source.
![image](https://user-images.githubusercontent.com/79684981/230526126-a2bb8962-462e-4703-bfec-a1a9154ca793.png)

**Comment by iNewmanity** [comment] 2023-04-07 08:46
> 

Thanks a lot for your help; Helped me add the Alpha Package, but i still got issues. Now the MGCB-Editor shows `System.NotSupportedException`. Any hint where I can find a solution to that :)

**Comment by gldraphael** [comment] 2023-04-10 11:22
For anyone looking for another example on how to use the alpha package: https://github.com/GameBased/mystery-island/pull/20

**Comment by iNewmanity** [comment] 2023-04-13 21:05
In the meanwhile i got this fixed but now have another problem: It wont build with the `dotnet build` command, with it saying ´error NU1102: Unable to find package MonoGame.Extended with version (>= 3.9.0-alpha0093)´

**Comment by purrplingcat** [comment] 2023-06-23 01:38
use 3.9.0-alpha doesn't work, because MGCB sas TiledMapImporter is invalid. If I look to the list of importers, there is none importer from Monogame extended.

**Comment by quentinmrzt** [comment] 2023-07-12 22:27
> > 
> 
> Thanks a lot for your help; Helped me add the Alpha Package, but i still got issues. Now the MGCB-Editor shows `System.NotSupportedException`. Any hint where I can find a solution to that :)
Hi, I'm a little late, but I had the same problem and I found the solution! By looking at the error in the code, I understood that it was the presence of 'chunks' that was causing the issue. 'Chunks' are divisions made in your .tmx file to handle large maps. Your map is probably set to 'infinite'; try exporting it with a fixed size, and that should solve your problem!

**Comment by quentinmrzt** [comment] 2023-07-12 22:27
> > 
> 
> Thanks a lot for your help; Helped me add the Alpha Package, but i still got issues. Now the MGCB-Editor shows `System.NotSupportedException`. Any hint where I can find a solution to that :)

Hi, I'm a little late, but I had the same problem and I found the solution! By looking at the error in the code, I understood that it was the presence of 'chunks' that was causing the issue. 'Chunks' are divisions made in your .tmx file to handle large maps. Your map is probably set to 'infinite'; try exporting it with a fixed size, and that should solve your problem!

**Comment by wiredmatt** [comment] 2024-01-12 04:18
> For anyone looking for another example on how to use the alpha package: [GameBased/mystery-island#20](https://github.com/GameBased/mystery-island/pull/20)

Using that exact config worked perfectly.

```xml
<ItemGroup>
    <PackageReference Include="MonoGame.Extended" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Extended.Collisions" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Extended.Content.Pipeline" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Extended.Input" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Extended.Tiled" Version="3.9.0-alpha0093" />
    <PackageReference Include="MonoGame.Framework.DesktopGL" Version="3.8.1.303" />
    <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.1.303" />
  </ItemGroup>
```

**Closed** 2024-05-28 02:30 UTC
