### ISSUE TITLE
FNA support?

### ISSUE THREAD

**Issue by therhinodude** [craftworkgames/MonoGame.Extended#619] opened 2019-07-19 16:06 UTC
So, short and sweet: is FNA supported / routinely tested against?

I see that there is a closed topic about supporting FNA going way back to 2015, but it seemed inconclusive (and probably out of date regardless as it was nearly 4 years old now).

Thanks in advance for answering...

**Comment by craftworkgames** [comment] 2019-07-20 00:45
The short answer is no, we don't officially support FNA.

However, there's nothing in Extended I'm aware of that would prohibit it from being used with FNA. Everything in Extended sits on top of the MonoGame API and since MonoGame, FNA and the old XNA all share the same API by design there should be no problem compiling Extended against it.

In theory the process should be relatively straightforward:

 1. Clone this repository to get the source code.
 2. Swap out the MonoGame references for FNA references.
 3. Compile and run.

I've never tried this myself but I'd be curious if you got it working. I'm going to close this issue now as I don't plan to officially support FNA anytime soon; but if you do manage to get it working I'd love to write up a blog post / documentation about how you did it. 

Also, if you do give it a go and run into any problems feel free to reopen this issue with more questions.

**Closed by craftworkgames** 2019-07-20 00:45 UTC
