### ISSUE TITLE
Static ServiceLocator class?

### ISSUE THREAD

**Issue by cupstudio** [craftworkgames/MonoGame.Extended#89] opened 2016-01-11 20:44 UTC
I have found [ServiceLocator] (http://gameprogrammingpatterns.com/service-locator.html) to be a useful way of providing access to shared components within a framework.  The nice thing is you can stick pretty much anything in it and get it back out again somewhere else, with only 1 static class being necessary.  Technically the Locator itself doesn't have to be static, but I prefer that over passing it throughout the entire framework.  You could also create a static instance, but where does that go so you always have it handy?

I saw that MonoGame itself has a ServiceLocator called GameServiceContainer which is minimal and non-static.  So either you create a static instance or pass it around.

I like the idea of the Locator performing maintenance on its objects as you see below.

What from MGE could be placed in a ServiceLocator?
* MouseListener
* KeyboardListener
* Removes need for the InputManager since all it does is contain and update anyway.
* A reusable default ViewportAdapter.  (I've created a custom one which implements my IAnchorable interface so that UI elements can be bound to the screen.)
* Reusable camera?

If you don't think this is a good fit for MGE that is ok, let me know what you think.

Here is an example of that class.  

````c#
    public static class ServiceProvider
    {
        #region [ Initialize ]
        public static void Initialize(Game gameInstance)
        {
            _game = gameInstance;
            Graphics = _game.GraphicsDevice;
            services = new Dictionary<Type, object>();
            Initialized = true;
        }
        #endregion


        #region [ Members ]
        private static Game _game;
        public static GraphicsDevice Graphics { get; private set; }
        private static Dictionary<Type, object> services;

        public static bool Initialized { get; private set; }
        #endregion


        #region [ Method: Update ]
        public static void Update(GameTime gameTime)
        {
            foreach (var service in services)
            {
                var serviceReference = service.Value as IUpdate;
                if (serviceReference != null)
                {
                    serviceReference.Update(gameTime);
                }
            }
        }
        #endregion


        #region [ Method: Draw ]
        public static void Draw(GameTime gameTime)
        {
            foreach (var service in services)
            {
                var serviceReference = service.Value as IDraw;
                if (serviceReference != null)
                {
                    serviceReference.Draw(gameTime);
                }
            }
        }
        #endregion


        #region [ Add / Remove Service ]
        public static void AddService(Type type, object provider)
        {
            if (!Initialized)
                throw new NotSupportedException("ServiceProvider not Initialized.");
            if (type == null)
                throw new ArgumentNullException("type");
            if (provider == null)
                throw new ArgumentNullException("provider");
            if (!Helper.IsAssignableFrom(type, provider))
                throw new ArgumentException("The provider does not match the specified service type!");

            services.Add(type, provider);
        }


        public static object GetService(Type type)
        {
            if (!Initialized)
                throw new NotSupportedException("ServiceProvider not Initialized.");
            if (type == null)
                throw new ArgumentNullException("type");

            object service;
            if (services.TryGetValue(type, out service))
                return service;

            return null;
        }


        public static void RemoveService(Type type)
        {
            if (!Initialized)
                throw new NotSupportedException("ServiceProvider not Initialized.");
            if (type == null)
                throw new ArgumentNullException("type");

            services.Remove(type);
        }


        public static void AddService<T>(T provider)
        {
            if (!Initialized)
                throw new NotSupportedException("ServiceProvider not Initialized.");
            AddService(typeof(T), provider);
        }


        public static T GetService<T>() where T : class
        {
            if (!Initialized)
                throw new NotSupportedException("ServiceProvider not Initialized.");

            var service = GetService(typeof(T));
            if (service == null)
                return null;

            return (T)service;
        }
        #endregion
    }
}
````

**Comment by craftworkgames** [comment] 2016-01-11 22:56
I've used service locators before. They make sense in certain situations. The problem is that they come with a significant amount of contention. The primary things people complain about when they see a service locator pattern are:

 - [They hide a classes dependencies in the implementation](http://stackoverflow.com/questions/1557781/whats-the-difference-between-the-dependency-injection-and-service-locator-patte)
 - [They can create a maintenance nightmare](http://stackoverflow.com/questions/22795459/is-servicelocator-anti-pattern)
 - [Global static state](http://programmers.stackexchange.com/questions/148108/why-is-global-state-so-evil)

That said, many of these complaints come from people that write business applications. It could be argued that writing games is a little bit different, to some degree.

Personally, I'm not a fan of service locators. I'm not completely opposed to them either. I think many of the arguments about them are valid but if you use them carefully they can be useful.

My personal preference is to use constructor injection. I don't have a problem with using something like a [Unity container](https://msdn.microsoft.com/en-us/library/ff647202.aspx) to inject those dependencies to get some of the benefits of a service locator without many of the downsides.

Anyway, to answer you're actual question, I don't really think introducing *another* service locator into MonoGame.Extended is a good idea. I also don't want to use service locators in the internals of MG.E for my own sanity.

But if people want to use service locators in their games I'm okay with that. We might need to make some changes to MG.E to allow them to do that, like introducing more interfaces.

If we are going to go down this path I think the most sensible thing to do is to look at how MG.E services could integrate with MonoGame's existing [GameServiceContainer](https://msdn.microsoft.com/en-us/library/microsoft.xna.framework.gameservicecontainer.aspx). I think if we do that, people will have a choice about how they use them without any constraints.

**Comment by cupstudio** [comment] 2016-01-11 23:10
One of the big reasons I wanted to bring this up was to learn more about this stuff, and the links you have provided are great.  I am going over Dependency Injection now.

As far as making some MGE components capable of being added to an external Locator, my first thought was for the InputHandlers.  I can add the manager as it is now to my own locator, but then its another hop to get to the actual Listener.  Would it be possible to change the InputListeners so they can be added directly (public constructors and Update), or do you think this is a bad idea?  I know you intended them to be used with the Manager, so I'm not sure if this would be a good enough reason to decouple those.

**Comment by craftworkgames** [comment] 2016-01-17 10:58
> Would it be possible to change the InputListeners so they can be added directly (public constructors and Update), or do you think this is a bad idea?

The problem with giving them public constructors is that if you construct one yourself, there's currently no way to actually use it with the `InputManager`. The only way to add a listener is to let the `InputManager` construct it for you.

    public T AddListener<T>();
    public T AddListener<T>(InputListenerSettings<T> settings);
    public IEnumerable<InputListener> Listeners;

Of course, we could change it to have a collection of listeners that implement `IList` so you could add the listeners to the collection directly. The downside is that it's a breaking change to the current API so it'd have to be a pretty compelling reason. Worth considering though.

**Comment by cupstudio** [comment] 2016-01-19 05:07
I worked around that by just saving the resulting listener in a var and adding to my own service locator class with that.  No worries.  :)

**Comment by craftworkgames** [comment] 2016-02-03 05:00
Okay so this issue has been open for a while now. At this stage I don't see any compelling reason to introduce a service locator. I'm closing this issue.

**Closed by craftworkgames** 2016-02-03 05:00 UTC
Labels: question
