### ISSUE TITLE
[Tiled] Work on Object Layers

### ISSUE THREAD

**Issue by rafaelalmeidatk** [craftworkgames/MonoGame.Extended#125] opened 2016-02-11 04:33 UTC
I need use the object layers but they haven't been implemented yet. How can I work on this? I am trying to understand the [TileMapReader.cs](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended/Maps/Tiled/TiledMapReader.cs) but I can't understand the `ReadInt32()` or other read stuff. Where I begin?

**Comment by craftworkgames** [comment] 2016-02-11 04:40
Okay cool.

So the `TiledMapReader` and `ReadInt32()` are part of how custom content importers work in MonoGame / XNA. A while ago I created [a tutorial](http://dylanwilson.net/creating-custom-content-importers-for-the-monogame-pipeline) on how to build custom content importers with MonoGame.

Essentially, you'll need to implement the bits for the the Content Pipeline first. For example, the `TiledMapReader` is paired with the [`TiledMapWriter`](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline/Tiled/TiledMapWriter.cs) in the Content Pipeline project. Every `Read` operation is paired with a `Write` operation.

That's how the raw TMX file gets compiled into an XNB file for MonoGame to load when you call `Content.Load<TiledMap>("my-map")`.

Have a go at it and PR changes into the `tiled-maps` branch please.

**Comment by rafaelalmeidatk** [comment] 2016-02-11 05:16
Ok, I think I got it. I see that you have done half of the way. How can I debug the `TiledMapWriter`?

**Comment by craftworkgames** [comment] 2016-02-11 05:21
Yes, debugging these things is rather difficult.

The only way that I've found that works kind of okay is unit tests. I've got some [Tiled Map Importer tests](https://github.com/craftworkgames/MonoGame.Extended/blob/develop/Source/MonoGame.Extended.Content.Pipeline.Tests/TiledMapImporterProcessorTests.cs) already that you should be able to use.

You should be able to put a break point in the test and run it in debug mode to step through the code and see what's going on.

**Comment by rafaelalmeidatk** [comment] 2016-02-11 05:33
Nice. I have a question. In the `TiledMapReaded` you iterate through the layers:

    for (var i = 0; i < layerCount; i++)
    {
        var layer = ReadLayer(reader, tiledMap);
        ReadCustomProperties(reader, layer.Properties);
    }

But how you store them?

**Comment by craftworkgames** [comment] 2016-02-11 05:39
When you pass a list into a method it gets passed by reference.

        private static void ReadCustomProperties(ContentReader reader, TiledProperties properties)
        {
            var count = reader.ReadInt32();

            for (var i = 0; i < count; i++)
                properties.Add(reader.ReadString(), reader.ReadString());
        }

So in this case, when you call `ReadCustomProperties(reader, layer.Properties);` it's actually changing the contents of the `layer.Properties` list. Does that make sense?

In hindsight this is a very strange thing to do in C#. Normally I would frown upon code like this. Maybe it would be better to change it so that `ReadCustomProperties` returned a list instead. Then the other code would look like this:

    layer.Properties = ReadCustomProperties(reader);

Would that make more sense to you?

**Comment by craftworkgames** [comment] 2016-02-11 05:44
I think the reason I did it that way was to maintain a private setter on the Properties properties.

    public TiledProperties Properties { get; private set; }

If you did it the other way we'd have to change them to public setters, meaning they could potentially be set to `null` by accident. Maybe that's not a big deal, but that's the thinking.

**Comment by rafaelalmeidatk** [comment] 2016-02-11 05:45
The second way is more understandable, but I think the first is acceptable, there's nothing wrong changing directly the list.

**Comment by rafaelalmeidatk** [comment] 2016-02-11 06:48
I wrote all the stuff to read the objects, but I cant build the .tmx file. Even before I do any change in the code, I receive this error:

> An unhandled exception of type 'System.InvalidOperationException' occurred in System.Xml.dll

> Additional information: There is an error in XML document (438, 27).

The line 438 of the .tmx is this:

    <object id="5" gid="26" x="117.818" y="751.879" width="128" height="128"/>

Context:

    <objectgroup name="Objects Layer 1">
     <object id="5" gid="26" x="117.818" y="751.879" width="128" height="128"/>
     <object id="6" gid="1" x="232.97" y="630.667" width="128" height="128"/>
    </objectgroup>

**Comment by craftworkgames** [comment] 2016-02-25 23:04
I think the only thing left to do on this is add it to the Tiled Maps demo project.

**Comment by rafaelalmeidatk** [comment] 2016-03-06 16:49
I think this issue need be fixed:

The values from XML can't contains points.
Example:

    <object id="5" gid="26" x="128" y="896" width="297" height="342">

Acceptable.

    <object id="5" gid="26" x="88.6061" y="880.848" width="297" height="342">

Unnaceptable, raises an error. I know the error comes from TmxObject.cs, the values aren't integers. If I change from integer to double or float, the values comes wrong. Changing the type of y from int to float:

    [XmlAttribute(DataType = "float", AttributeName = "y")]
    public float Y { get; set; }

Result:

![](https://cloud.githubusercontent.com/assets/11896398/12971469/9d9e2e74-d082-11e5-8af7-d9aa86ff3382.png)

**Comment by craftworkgames** [comment] 2016-03-06 21:48
Yes, this is very weird. Maybe it's got something to do with how the XML deserializer works? Maybe try doing some googling and see if you can find others with this issue.

**Comment by craftworkgames** [comment] 2016-03-06 22:17
Nevermind. I worked it out.

The problem is actually in `TiledMapReader` when it's reading the properties from the XNB file. It's expecting them to be int's when they are actually floats.

                var x = reader.ReadInt32();
                var y = reader.ReadInt32();
                var width = reader.ReadInt32();
                var height = reader.ReadInt32();

Should be:

                var x = reader.ReadSingle();
                var y = reader.ReadSingle();
                var width = reader.ReadSingle();
                var height = reader.ReadSingle();

I'm working on this now. I'll have something checked in shortly.

**Comment by craftworkgames** [comment] 2016-03-06 23:15
I've committed the initial fix but I noticed a number of other properties are not being read and written. In other words, there's still plenty of stuff to do before object layers are fully supported.

I'm going to keep working on this whenever I get spare time.

**Comment by craftworkgames** [comment] 2016-03-07 12:10
Almost everything is done on this now. All of the properties for object layers is being loaded.

The only thing left I'd like to do is add the ability to render the object layers to the screen. Rendering shapes would be an option, but turned off by default.

**Comment by HyperionMT** [comment] 2016-11-07 19:11
@craftworkgames, I'm looking to finish up the last bit of work here but wanted to revisit your comment on drawing the objects.  I agree we should be rendering any objects created as part of "Insert Tile" on the object layer however it was my interpretation that shapes were not a visual construct and shouldn't be rendered outside of the Tiled editor.  I think the fact that there's no way to customize how they appear (color, fill, border thickness) in the Tiled editor supports that.  If you still think we should support drawing the shapes I can certainly implement that as well but I wanted to check first.

**Comment by craftworkgames** [comment] 2016-11-08 12:24
> If you still think we should support drawing the shapes I can certainly implement that as well but I wanted to check first.

I'd rather not clutter up the renderer with shape rendering code..

However, there is one use case that makes sense to me and that is when you're trying to debug a problem. Now that we have the ability to have multiple renderers I wonder if it might make sense to have a debug renderer separate from the "normal" renderer.

If you're super keep to do it you can, but I'm happy to leave it out for now.

**Comment by HyperionMT** [comment] 2016-11-08 19:08
> If you're super keep to do it you can, but I'm happy to leave it out for now.

Nope, you pretty much summed up how I feel I just wanted to make sure I did everything required to close this issue. I'll finish up rendering of tiles in object layers and submit a PR.

**Comment by HyperionMT** [comment] 2016-11-09 00:16
Ran into an unexpected issue when testing against the Platformer demo.  I didn't realize TiledObjectType.Tile objects were being used as spawn points.  This seems a little weird to me as you wouldn't want those to display on the map or you'd end up with something like this:
![image](https://cloud.githubusercontent.com/assets/23129284/20122678/8305f3e0-a5e7-11e6-9d83-275db0e40dc6.png)

Am I just thinking about this wrong?  Should I be coming up with a way to deal with this or can we just convert those to shapes?

**Comment by craftworkgames** [comment] 2016-11-10 10:44
> When in doubt, make it configurable! So that's what I did, now you can pass in a MapRendererConfig object to turn object layer drawing on/off

Sorry for the late reply. This is exactly what I was going to say. You beat me to the punch 👍 

There's probably going to be lots of creative ways people will want to use the editor. We don't have to support anything and everything but it's nice to make a few things configurable to allow for this.

One the nice things about doing spawn points this way is that you can see in the editor how things are going to look and fit together. It's a nice level editing experience. 

There's obviously going to be other reasons people want to place tiles as objects though, so I think you made the right choice.

**Closed** 2016-11-10 10:48 UTC
Labels: enhancement
