### ISSUE TITLE
Can't load .tmx files 

### ISSUE THREAD

**Issue by Selviniahh** [craftworkgames/MonoGame.Extended#810] opened 2023-05-20 23:29 UTC
Can't load .tmx files. I loaded required nuget packages and added required .dll to the the ContentManager.

**Comment by RicharDKcoder** [comment] 2023-05-25 09:27
i think its version not same 
monogame version 3.8.1
monogame extended verison 3.8.0

**Comment by Gandifil** [comment] 2023-09-03 14:15
May be, Duplicate of #783. Please, check and answer here.

However, try to load dev version of Monogame.Extended. (instructions in README).

**Comment by AristurtleDev** [comment] 2024-05-29 17:09
This issue has been solved in `develop` and will be part of the 4.0.0 release.

**Closed by AristurtleDev** 2024-05-29 17:09 UTC
Labels: bug
