### ISSUE TITLE
NuGet Packages

### ISSUE THREAD

**Issue by LithiumToast** [craftworkgames/MonoGame.Extended#329] opened 2017-01-09 05:01 UTC
When Graphics and Tiled code was separated into their own libraries, people can't access the latest Graphics and Tiled code from the NuGet package(s).

From Gitter Chat:

> @jeffol
> Hey guys.. finally got some free time to play with MonoGame Extended again. Tried updating my project to beyond what I was using before (0.6.247) to get the latest resolved issues. Well, I discovered that Tiled map support has been removed, or separated from the project, and isn't available anywhere... Doesn't seem like such a logical change to me, as maps are probably the most attractive feature of the whole library. Anyway, I'm stuck at 0.6.247 until then. If I understand right, the idea is to separate them into two useful libraries. Not that useful when it's unavailable unfortunately. It looks like somebody just posted an issue about how the Tiled package is just altogether missing as well. http://community.monogame.net/t/how-to-use-fullmaprenderer-in-project/8605

**Comment by LithiumToast** [comment] 2017-01-09 05:05
I tried fixing this in #330

**Comment by jeffol** [comment] 2017-01-09 07:53
This is all fixed now. @craftworkgames Updated the available nuget packages and everything is working as intended.
![nuget](https://cloud.githubusercontent.com/assets/3392831/21760016/73aa4642-d60e-11e6-84e8-4af3e6c94f68.png)

**Comment by Sopheria** [comment] 2017-01-09 14:27
Thanks for handling this so promptly! I was having problems with this earlier. So 

`PM> Install-Package MonoGame.Extended.Tiled`

should work?

**Comment by jeffol** [comment] 2017-01-09 18:28
@Sopheria Hey there, you need to target the Craftworkgames build server to access the pre-release nuget packages. See this page for details on how to do that: https://github.com/craftworkgames/MonoGame.Extended/wiki/How-to-use-the-pre-release-NuGet-packages

Try using the nuget package manager interface to browse to the craftworks games server to find the correct packages.

**Closed** 2017-03-20 11:23 UTC
