### ISSUE TITLE
BoxingViewportAdapter Crash on Window resize/movement with DirectX

### ISSUE THREAD

**Issue by JoJo1541** [craftworkgames/MonoGame.Extended#732] opened 2021-03-31 15:31 UTC
Title says it all I think. 
If I create a simple implementation of a game and create a BoxingViewportAdapter I get a null reference exception after moving/resizing the game window.
Same Code works fine if OpenGL is used instead.

Stack Trace:
`NullReferenceExcpetion at MonoGame.Extended.ViewportAdapters.BoxingViewportAdapter.OnClientSizeChanged(Object sender, EventArgs eventArgs)

at System.Windows.Forms.Form.OnResizeEnd(EventArgs e)
at System.Windows.Forms.Form.WmExitSizeMove(Message& m)
at System.Windows.Forms.Form.WndProc(Message& m)
at Microsoft.Xna.Framework.Windows.WinFormsGameForm.WndProc(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by AristurtleDev** [comment] 2024-05-29 18:35
@JoJo1541 

I just created simple game referencing the `develop` branch using the following code

```cs
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
using MonoGame.Extended;
using MonoGame.Extended.ViewportAdapters;

namespace TestDx;

public class Game1 : Game
{
    private GraphicsDeviceManager _graphics;
    private SpriteBatch _spriteBatch;
    private OrthographicCamera _camera;

    public Game1()
    {
        _graphics = new GraphicsDeviceManager(this);
        Content.RootDirectory = "Content";
        IsMouseVisible = true;
        Window.AllowUserResizing = true;
    }

    protected override void Initialize()
    {
        base.Initialize();
        var viewportAdapter = new BoxingViewportAdapter(Window, GraphicsDevice, 800, 480);
        _camera = new OrthographicCamera(viewportAdapter);
    }

    protected override void LoadContent()
    {
        _spriteBatch = new SpriteBatch(GraphicsDevice);
    }


    protected override void Draw(GameTime gameTime)
    {
        GraphicsDevice.Clear(Color.CornflowerBlue);

        var transformMatrix = _camera.GetViewMatrix();
        _spriteBatch.Begin(transformMatrix: transformMatrix);
        _spriteBatch.DrawRectangle(new RectangleF(250, 250, 50, 50), Color.Black, 1f);
        _spriteBatch.End();

        base.Draw(gameTime);
    }
}
```

Using this, I am unable to reproduce your issue on either a WIndowDX or OpenGL project.
Given how old this issue is, I'm going to close it.  If you can recreate the issue using the `develop` branch and provide a minimal reproduction example, it can be looked into further at that point.

**Closed by AristurtleDev** 2024-05-29 18:35 UTC
Labels: bug
